apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/flux-iac/charts
  ref:
    semver: ">=0.16.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tofu-controller
      version: "0.16.0-rc.5"
      sourceRef:
        kind: OCIRepository
        name: tofu-controller
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
